"""The generic worklist solver (D26, Q2.1), tested standalone on a toy
lattice -- both directions, both joins -- before any real analysis is
wired to it. A solver bug here would otherwise look like three unrelated
analysis bugs later.
"""

from __future__ import annotations

from clens.core.cfg import BasicBlock, BlockKind, ControlFlowGraph, EdgeLabel
from clens.core.dataflow import Analysis, Direction, solve


def _diamond() -> tuple[ControlFlowGraph, dict[str, BasicBlock]]:
    """ENTRY -> A -> {B, C} -> D -> EXIT: the smallest graph with a real
    join point, so intersection and union actually differ."""
    entry = BasicBlock(id=0, kind=BlockKind.ENTRY)
    exit_ = BasicBlock(id=0, kind=BlockKind.EXIT)
    a = BasicBlock(id=1, kind=BlockKind.NORMAL)
    b = BasicBlock(id=2, kind=BlockKind.NORMAL)
    c = BasicBlock(id=3, kind=BlockKind.NORMAL)
    d = BasicBlock(id=4, kind=BlockKind.NORMAL)

    entry.add_successor(a, EdgeLabel.FALLTHROUGH)
    a.add_successor(b, EdgeLabel.TRUE)
    a.add_successor(c, EdgeLabel.FALSE)
    b.add_successor(d, EdgeLabel.FALLTHROUGH)
    c.add_successor(d, EdgeLabel.FALLTHROUGH)
    d.add_successor(exit_, EdgeLabel.FALLTHROUGH)

    cfg = ControlFlowGraph(
        function_name="toy", entry=entry, exit=exit_, blocks=[entry, a, b, c, d, exit_]
    )
    return cfg, {"entry": entry, "a": a, "b": b, "c": c, "d": d, "exit": exit_}


def _name_generating_transfer(names: dict[int, str]):
    def transfer(block: BasicBlock, in_set: frozenset[str]) -> frozenset[str]:
        return in_set | {names[id(block)]}

    return transfer


def _union(sets: list[frozenset[str]]) -> frozenset[str]:
    result: set[str] = set()
    for s in sets:
        result |= s
    return frozenset(result)


def _intersection(sets: list[frozenset[str]]) -> frozenset[str]:
    result = set(sets[0])
    for s in sets[1:]:
        result &= s
    return frozenset(result)


def test_forward_union_accumulates_along_every_path():
    cfg, blocks = _diamond()
    names = {id(b): name for name, b in blocks.items()}
    analysis = Analysis(
        direction=Direction.FORWARD,
        join=_union,
        transfer=_name_generating_transfer(names),
        boundary=frozenset(),
        initial=frozenset(),
    )
    result = solve(cfg, analysis)
    _, out_a = result[id(blocks["a"])]
    assert out_a == {"entry", "a"}
    _, out_d = result[id(blocks["d"])]
    # D is reached through both B and C, so a forward *may* (union) fact
    # picks up everything from either branch.
    assert out_d == {"entry", "a", "b", "c", "d"}


def test_forward_intersection_needs_full_initial_value():
    """The classic bug (skill doc): a must-analysis initialises non-entry
    blocks to the *full* universe, not empty -- otherwise intersection
    collapses to empty on the very first join and nothing is ever
    considered "on every path"."""
    cfg, blocks = _diamond()
    names = {id(b): name for name, b in blocks.items()}
    universe = frozenset(names.values())
    analysis = Analysis(
        direction=Direction.FORWARD,
        join=_intersection,
        transfer=_name_generating_transfer(names),
        boundary=frozenset(),
        initial=universe,
    )
    result = solve(cfg, analysis)
    # D's two predecessors carry {entry, a, b} and {entry, a, c} into the
    # join; only "entry" and "a" (both upstream of the branch) are common
    # to every path, so the join into D is their intersection.
    in_d, out_d = result[id(blocks["d"])]
    assert in_d == {"entry", "a"}
    assert out_d == {"entry", "a", "d"}


def test_backward_union_propagates_from_exit():
    cfg, blocks = _diamond()
    names = {id(b): name for name, b in blocks.items()}
    analysis = Analysis(
        direction=Direction.BACKWARD,
        join=_union,
        transfer=_name_generating_transfer(names),
        boundary=frozenset(),
        initial=frozenset(),
    )
    result = solve(cfg, analysis)
    _, out_a = result[id(blocks["a"])]
    # Backward: A's successors are B and C, so A's `in` picks up facts
    # generated by both branches and everything downstream of them.
    assert out_a == {"a", "b", "c", "d", "exit"}
    in_exit, _ = result[id(blocks["exit"])]
    assert in_exit == frozenset()


def test_backward_intersection_only_keeps_common_facts():
    cfg, blocks = _diamond()
    names = {id(b): name for name, b in blocks.items()}
    universe = frozenset(names.values())
    analysis = Analysis(
        direction=Direction.BACKWARD,
        join=_intersection,
        transfer=_name_generating_transfer(names),
        boundary=frozenset(),
        initial=universe,
    )
    result = solve(cfg, analysis)
    _, out_a = result[id(blocks["a"])]
    # B and C each carry {exit, d} plus their own name into the join into
    # A; only the common {exit, d} survives the intersection.
    assert out_a == {"exit", "d", "a"}


def test_orphan_block_with_no_predecessors_uses_initial_value():
    """A block that is not the direction's entry point and has no
    predecessors (e.g. genuinely unreachable code) must not crash the
    join -- it falls back to `initial` rather than joining an empty list."""
    entry = BasicBlock(id=0, kind=BlockKind.ENTRY)
    exit_ = BasicBlock(id=0, kind=BlockKind.EXIT)
    reachable = BasicBlock(id=1, kind=BlockKind.NORMAL)
    orphan = BasicBlock(id=2, kind=BlockKind.NORMAL)
    entry.add_successor(reachable, EdgeLabel.FALLTHROUGH)
    reachable.add_successor(exit_, EdgeLabel.FALLTHROUGH)
    # `orphan` is deliberately left with no predecessors.
    cfg = ControlFlowGraph(
        function_name="toy", entry=entry, exit=exit_, blocks=[entry, reachable, orphan, exit_]
    )
    analysis: Analysis[frozenset[str]] = Analysis(
        direction=Direction.FORWARD,
        join=_union,
        transfer=lambda block, in_set: in_set,
        boundary=frozenset(),
        initial=frozenset({"sentinel"}),
    )
    result = solve(cfg, analysis)
    in_orphan, out_orphan = result[id(orphan)]
    assert in_orphan == {"sentinel"}
    assert out_orphan == {"sentinel"}
